<template>
	<div class="bodyContainer">
		<h1 class="text-center">The beginning of the internet</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean lobortis turpis quis lectus semper, in luctus justo auctor. Proin eu libero ac mi dignissim tempus at vitae libero. Etiam porta tempus erat, in maximus nibh. In neque leo, venenatis mollis ante eget, viverra molestie diam. Praesent lacinia urna et odio lobortis, feugiat pharetra libero condimentum. Ut mollis, dui nec eleifend finibus, sapien tellus pellentesque lectus, at tincidunt velit lorem a nunc. Vivamus id metus dictum, finibus libero non, malesuada nibh. Mauris enim sapien, lacinia a purus tincidunt, tincidunt ornare diam. Ut non libero condimentum, fermentum enim at, fringilla purus. Curabitur placerat laoreet tellus, id tristique metus egestas id. Sed porta libero rhoncus magna iaculis, sit amet pretium est consequat. Pellentesque bibendum sem eu orci vehicula, quis tincidunt metus elementum. Nam porta eget est sit amet ultricies. Nullam elit ligula, accumsan quis tempor eu, vulputate nec arcu.

			Pellentesque quis magna sem. Donec ac tellus quis ex ornare pellentesque. In suscipit, velit ac blandit ornare, eros elit facilisis lorem, at lobortis erat enim ac purus. Vestibulum sodales mauris dui. Fusce lacinia augue id velit feugiat luctus. Proin a nulla luctus, aliquet felis non, malesuada mauris. Etiam pretium lorem libero, et interdum erat venenatis id. Nullam ornare, velit at rutrum congue, felis ligula imperdiet mi, nec condimentum leo nisi et orci. Aenean tellus massa, luctus placerat venenatis ut, rhoncus in nulla. Proin mattis aliquet leo ut lobortis. Duis semper purus nec enim volutpat gravida. Vestibulum nisi massa, tristique quis dui ut, vehicula aliquet turpis. Nullam a egestas mi. Nulla facilisi. Donec dui dui, commodo non placerat in, auctor id lacus.

			Suspendisse sit amet sodales elit. Nam eu laoreet est. Donec aliquet ante nec eleifend tempor. Vivamus a molestie leo, non aliquam nibh. Praesent consequat purus metus. Fusce accumsan nisl nec blandit posuere. Sed faucibus magna ex, ut condimentum quam malesuada eu. Ut feugiat luctus elit eu consequat. Morbi mi tellus, convallis at tristique mattis, suscipit eget nibh. Pellentesque tincidunt elementum ante. Aliquam eget nisl risus. Aliquam sagittis urna tincidunt, rhoncus risus a, auctor felis. Vivamus lacinia mollis aliquet. Praesent tellus augue, faucibus maximus efficitur non, facilisis non mauris.

			Donec suscipit, mi eget pretium pharetra, ipsum risus convallis est, pharetra tristique arcu elit quis leo. Aliquam sit amet convallis erat. Donec tempor felis sit amet mi facilisis, non venenatis dolor venenatis. Pellentesque euismod posuere magna sed laoreet. Pellentesque quis nisl ullamcorper, pulvinar mauris et, congue mauris. Vestibulum sagittis euismod augue. Sed pharetra ex nec mattis ullamcorper.

			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ornare, nunc a varius dignissim, ex dui lobortis purus, nec elementum dolor urna eu nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean feugiat, lorem nec semper luctus, tellus leo finibus odio, et accumsan ipsum erat sed sem. Vivamus eu massa enim. In vitae pellentesque urna. Cras congue laoreet fermentum. Aliquam tellus lacus, accumsan vitae massa vel, dignissim gravida nisl. Donec tellus eros, commodo placerat mattis vel, fermentum vel ligula. Mauris quis eleifend lacus, id mattis leo.

			Quisque rhoncus at enim sed ultrices. Integer laoreet est massa, id rutrum dolor interdum sed. Cras malesuada mollis lectus, et euismod est dictum in. Mauris a mollis quam. Aliquam convallis augue eu tortor porttitor pharetra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer sagittis neque ac lorem tempus, vitae bibendum tellus imperdiet. Ut maximus metus ut erat lacinia efficitur. Nullam sit amet metus id mi ultrices tristique quis at leo. Phasellus congue commodo nisl, in fermentum odio venenatis eu. Maecenas vel imperdiet massa. Vestibulum blandit purus id lorem eleifend, eu volutpat metus fermentum. Etiam vel ipsum ac tellus lacinia blandit vel eget dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus ut urna eu sapien semper fringilla elementum nec ante. Nulla facilisi.

			Cras consectetur, elit venenatis viverra maximus, massa nulla laoreet dui, ut porttitor neque eros nec sem. Vivamus non sapien imperdiet, laoreet metus vel, egestas ipsum. Quisque dui arcu, tincidunt sit amet tristique at, condimentum ac quam. Nunc nec dapibus elit, eu cursus libero. Nam at mattis dolor, ut dictum eros. Phasellus semper neque ornare nunc pharetra auctor. Fusce lobortis consequat feugiat. Quisque vel dictum nibh. Aliquam imperdiet ipsum eu sem dictum, nec blandit urna feugiat. Phasellus ex elit, mattis at varius ut, convallis nec nunc. Suspendisse id arcu a justo ultricies gravida ut non ipsum.

			Suspendisse potenti. Pellentesque non tristique tellus. Duis efficitur magna nec sagittis bibendum. Vestibulum blandit nisl eu lorem volutpat, sit amet suscipit sapien feugiat. Aliquam tortor urna, molestie ultricies imperdiet ac, ullamcorper quis diam. Vivamus posuere elit et massa lacinia, vitae posuere lacus rhoncus. Phasellus imperdiet lorem eu mauris finibus, sed fringilla purus ornare. Nunc ut nunc bibendum, lacinia tortor quis, cursus nunc. Nulla dui urna, sagittis sed vulputate a, rutrum mollis libero. Suspendisse sagittis sed magna id convallis. Nulla sem orci, pretium et iaculis vel, rhoncus eu tortor. Ut ut mi convallis, congue sapien in, rhoncus velit. Nulla faucibus purus a mollis sodales.

			Phasellus non sapien sed orci vestibulum fermentum. Aenean a velit diam. Aliquam elit arcu, facilisis vel tincidunt nec, feugiat et sem. Pellentesque erat leo, aliquet eu est vitae, ornare finibus massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum pellentesque nisi turpis, ac pellentesque enim posuere vitae. Phasellus at viverra orci, vitae vestibulum elit. Morbi eleifend sapien non augue porta lobortis. Donec pharetra risus sed lectus dictum, a accumsan dui hendrerit. Aenean imperdiet orci et sodales tincidunt. Proin fermentum tortor eget felis imperdiet interdum. Vestibulum consectetur facilisis justo. Pellentesque at quam id nisl gravida vestibulum. Vestibulum bibendum massa eget augue commodo dictum. Morbi facilisis magna in volutpat sagittis.

			Duis imperdiet elit a mollis finibus. Nunc vitae ante sit amet ante molestie vestibulum. Nullam eu nunc eu elit vulputate iaculis. Vestibulum at leo dictum, euismod nulla quis, cursus dolor. Nulla ultrices dapibus ante, ac auctor nulla aliquam vitae. Fusce luctus erat ipsum, ac euismod quam luctus at. In at laoreet augue. Nam eu nisi interdum, pretium tellus vel, eleifend mi.</p>
	</div>
</template>
<script>
	import {internetLinks} from '../service/SidebarLinks'
	import bus from '../service/Bus';
	export default{
		name: 'internetBeginning',
		created(){
			bus.$emit('set-nav-links', internetLinks);
		}
	}
</script>

